### PR TITLE
Enable vhost subdomain support

### PR DESCRIPTION
**Pull request by tomatlscomm**
vhost subdomains are type = vhostsubdomain
we also need to use other remote API functions in order to update ISPC data

### CODE REVIEW

**Comment by sjau** [comment]
you want to enable SAN support with that?

**Comment by tomatlscomm** [comment]
Sorry. I don't understand SAN.
In ISPConfig, you can enable subdomain to be real vhost (and not a simple redirection like by default).

With the few modification i made to your script, it enable the support of this subdomainvhost.
Otherwise you get some exceptions in your script because sites_web_domain_get and sites_web_domain_update can't work with vhost subdomains.

Regards

**Comment by sjau** [comment]
actually, it works just fine:


le2ispc pastebin.simplylinux.ch

-> https://pastebin.simpylinux.ch

**Comment by tomatlscomm** [comment]
Sorry but it can't work with vhostsubdomain.
Juste for example, in your script, /web/ folder is hardcoded.
When you create a vhostsubdomain, the webroot path can't be /web/.

If you wan't to check, it can be enabled in ISPC panel > System > Main config > Sites > Create Subdomains as web site

**Comment by sjau** [comment]
sorry, my mistake :) Now I understand.

**Pull request merged**
